//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_TraficoMadrid.WS_TraficoMadrid_ServiceBUS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_TraficoMadrid_ServiceBUS.ServiceBusSoap")]
    public interface ServiceBusSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetRouteLines(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteLines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetRouteLinesAsync(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteLinesRoute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetRouteLinesRoute(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteLinesRoute", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetRouteLinesRouteAsync(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCalendar(string idClient, string PassKey, string SelectDateBegin, string SelectDateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalendar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCalendarAsync(string idClient, string PassKey, string SelectDateBegin, string SelectDateEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetListLines(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListLines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetListLinesAsync(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListLinesExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetListLinesExtend(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListLinesExtend", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetListLinesExtendAsync(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetGroups(string idClient, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetGroupsAsync(string idClient, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimesLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetTimesLines(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimesLines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetTimesLinesAsync(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimeTableLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetTimeTableLines(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimeTableLines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetTimeTableLinesAsync(string idClient, string PassKey, string SelectDate, string Lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNodesLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetNodesLines(string idClient, string PassKey, string Nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNodesLines", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetNodesLinesAsync(string idClient, string PassKey, string Nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadisticaCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode EstadisticaCache(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadisticaCache", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EstadisticaCacheAsync(string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceBusSoapChannel : WS_TraficoMadrid.WS_TraficoMadrid_ServiceBUS.ServiceBusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBusSoapClient : System.ServiceModel.ClientBase<WS_TraficoMadrid.WS_TraficoMadrid_ServiceBUS.ServiceBusSoap>, WS_TraficoMadrid.WS_TraficoMadrid_ServiceBUS.ServiceBusSoap {
        
        public ServiceBusSoapClient() {
        }
        
        public ServiceBusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetRouteLines(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetRouteLines(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetRouteLinesAsync(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetRouteLinesAsync(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Xml.XmlNode GetRouteLinesRoute(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetRouteLinesRoute(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetRouteLinesRouteAsync(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetRouteLinesRouteAsync(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Xml.XmlNode GetCalendar(string idClient, string PassKey, string SelectDateBegin, string SelectDateEnd) {
            return base.Channel.GetCalendar(idClient, PassKey, SelectDateBegin, SelectDateEnd);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCalendarAsync(string idClient, string PassKey, string SelectDateBegin, string SelectDateEnd) {
            return base.Channel.GetCalendarAsync(idClient, PassKey, SelectDateBegin, SelectDateEnd);
        }
        
        public System.Xml.XmlNode GetListLines(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetListLines(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetListLinesAsync(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetListLinesAsync(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Xml.XmlNode GetListLinesExtend(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetListLinesExtend(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetListLinesExtendAsync(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetListLinesExtendAsync(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Xml.XmlNode GetGroups(string idClient, string PassKey) {
            return base.Channel.GetGroups(idClient, PassKey);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetGroupsAsync(string idClient, string PassKey) {
            return base.Channel.GetGroupsAsync(idClient, PassKey);
        }
        
        public System.Xml.XmlNode GetTimesLines(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetTimesLines(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetTimesLinesAsync(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetTimesLinesAsync(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Xml.XmlNode GetTimeTableLines(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetTimeTableLines(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetTimeTableLinesAsync(string idClient, string PassKey, string SelectDate, string Lines) {
            return base.Channel.GetTimeTableLinesAsync(idClient, PassKey, SelectDate, Lines);
        }
        
        public System.Xml.XmlNode GetNodesLines(string idClient, string PassKey, string Nodes) {
            return base.Channel.GetNodesLines(idClient, PassKey, Nodes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetNodesLinesAsync(string idClient, string PassKey, string Nodes) {
            return base.Channel.GetNodesLinesAsync(idClient, PassKey, Nodes);
        }
        
        public System.Xml.XmlNode EstadisticaCache(string password) {
            return base.Channel.EstadisticaCache(password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EstadisticaCacheAsync(string password) {
            return base.Channel.EstadisticaCacheAsync(password);
        }
    }
}
